### ISSUE TITLE
Logomark proposal

### ISSUE THREAD

**Issue by mevCJ** [DigitalRuby/ExchangeSharp#222]
Hi Sir, I am a part-time graphic designer and I want to contribute to your project by proposing a logomark for ExchangeSharp. If you are interested in using the design, I will send you the files or incorporate the logo into the readme file in a pull request. Feel free to inform me if you want any modifications to be made. The details of the logomark are attached below:

### Logomark
![fische-100](https://user-images.githubusercontent.com/35603131/43363952-1c620822-9343-11e8-9f45-7a2f335b448b.jpg)
![artboard 7-100](https://user-images.githubusercontent.com/35603131/43363959-3acbee68-9343-11e8-9489-e613397f39f4.jpg)

### Combination mark
![artboard 9-100](https://user-images.githubusercontent.com/35603131/43363962-45b1a264-9343-11e8-8cf5-a2c0386a1349.jpg)

### Variations
![artboard 10-100](https://user-images.githubusercontent.com/35603131/43363964-4e06a6f8-9343-11e8-884c-96869b288235.jpg)

## About the logo
![artboard 8-100](https://user-images.githubusercontent.com/35603131/43363968-5fc6d110-9343-11e8-8b48-81e51a773e76.jpg)
* The logo is a combination of E, # sign and a coin shape (which is typically used in cryptocurrency logo).
* The color of the original logo is used.

Hope you'll like it.

Thank you.

**Comment by bichuga** [comment]
Really solid. Great colors and font choice.

Just to put another idea on the table, if you drop the dot in the middle of
the #, it looks like a puzzle piece. Developers are plugging in their piece
into ExchangeSharp to complete their crypto bot picture. ExchangeSharp is
all of the scaffolding and support surrounding the code that will be
plugged in.

[image: image.png]
Either way I think it's great.

**Comment by bichuga** [comment]
![image](https://user-images.githubusercontent.com/9372553/43376915-3bacc31e-9372-11e8-9a4e-926279c3ba96.png)

**Comment by mevCJ** [comment]
@bichuga great concept! @jjxtra what do you think?

**Comment by jjxtra** [comment]
Sounds good to me!
