### ISSUE TITLE
Okex api error 10007 - "Signature does not match"

### ISSUE THREAD

**Issue by vlebedev7** [DigitalRuby/ExchangeSharp#519]
When I'm trying to make an Okex api call (for example GetAmountsAsync) I get error 10007 - "Signature does not match" as a response. Howerer if I try this api implementaion:
https://github.com/okcoin-okex/open-api-v3-sdk
then it works fine with the same api key credentials

**Comment by vslee** [comment]
Thanks for filing this bug. If you send a pull request with the solution, we'll be happy to merge it. If you don't know how, you can also post the updated code here.

**Comment by vlebedev7** [comment]
I found the source of this error. It happens because I try to use okex api v3 (which is apparantly not supported yet by this library). I can still use api v1, but okex says they will turn off v3 by the end of this month, which means that we won't be able to use okex with this library anymore

**Comment by vslee** [comment]
Good find. If you want to update the methods important to you to V3, I can merge those changes. In the meantime, I'll probably release a new NuGet today.

**Comment by BZ-CO** [comment]
@vslee, we can close this one.
