### ISSUE TITLE
FTX API Implementation

### ISSUE THREAD

**Issue by Plumbly** [DigitalRuby/ExchangeSharp#634]
Hi all,

Is anyone planning, or currently in the process of, integrating [FTX](https://ftx.com/)? If not, I will look to implement it myself and make a pull request. I just wanted to make sure I don't spend time on it if someone is already on it.

**Comment by Plumbly** [comment]
Just a quick update that I should be ready to make a pull request for this exchange implementation by the end of the week.

**Comment by bezysoftware** [comment]
Are you planning to add withdrawals (+withdrawal fees)? I think it shouldn't be too complicated based on their docs

**Comment by Plumbly** [comment]
I did plan to do it at some point, as I will need it for the project I work on, but didn't need it right now. However, you are right, it doesn't look like too much work so, will try find some time to add it.

**Comment by bezysoftware** [comment]
I think there's also an issue with the namespace. It needs to be in "ExchangeSharp" namespace for the lookup by name to work: https://github.com/jjxtra/ExchangeSharp/blob/master/src/ExchangeSharp/API/Exchanges/_Base/ExchangeName.cs#L50

**Comment by vslee** [comment]
> I think there's also an issue with the namespace. It needs to be in "ExchangeSharp" namespace for the lookup by name to work: https://github.com/jjxtra/ExchangeSharp/blob/master/src/ExchangeSharp/API/Exchanges/_Base/ExchangeName.cs#L50

Yes, we'll have to fix that before the next NuGet

**Comment by Plumbly** [comment]
I have now fixed the namespace of the FTX exchange.
