### ISSUE TITLE
Binance OnGetTickersAsync throws InvalidDataException

### ISSUE THREAD

**Issue by BZ-CO** [DigitalRuby/ExchangeSharp#785]
Currently we identify base/quote currencies by calling `OnGetMarketSymbolsMetadataAsync()`.
If instrument is going to be delisted soon it may be removed from the metadata response, while it still remains in the ticker response.
This leads to throwing an exception and failing to return the remaining valid ticker data.

`ParseTickerAsync()` should be wrapped in try block.

Will submit PR with the fix in a minute.

**Comment by jjxtra** [comment]
Thank you

**Comment by vslee** [comment]
Thanks for your contribution! Your code changes are now available in the prerelease build: https://dev.azure.com/DigitalRuby/DigitalRuby/_artifacts/feed/DigitalRuby
