### ISSUE TITLE
Need help Poloniex signature generation

### ISSUE THREAD

**Issue by BZ-CO** [DigitalRuby/ExchangeSharp#796]
I've updated the public REST endpoints to the new Poloniex API, but I've got stuck at the signature generation.
If someone can help with that it would be great, so I can add the authenticated endpoints as well.

**Comment by vslee** [comment]
Thanks for updating the public endpoints. I can't help with the signature generation because I don't have a Poloniex acct (and they don't offer them in the US anyways).  
What error are you getting?

**Comment by BZ-CO** [comment]
I'm getting 401 response.

I am using the provided js example as reference:
https://github.com/poloniex/polo-spot-sdk/blob/BRANCH_SANDBOX/signature_demo/signature_nodejs_demo.md

Both sample and my payload looks identical and both gets 401 response.

**Comment by vslee** [comment]
> both gets 401 response.

You're saying that the example nodejs code also gets a 401 response?

**Comment by BZ-CO** [comment]
Yes . I've found third party js library, which seems to work. I will try to reproduce the steps from there.
