### ISSUE TITLE
Coinbase is not authenticating, at least in sandbox

### ISSUE THREAD

**Issue by artemiusgreat** [DigitalRuby/ExchangeSharp#832]
Trying to get authenticated by Coinbase Advanced API Sandbox.

```
var exchange = await ExchangeAPI.GetExchangeAPIAsync(ExchangeName.Coinbase);
exchange.LoadAPIKeysUnsecure(ConsumerKey, ConsumerSecret, ConsumerPassword);
exchange.BaseUrlWebSocket = "wss://ws-feed-public.sandbox.exchange.coinbase.com";
exchange.BaseUrl = "https://api-public.sandbox.exchange.coinbase.com";
```

Getting `Invalid passphrase` exception when executing some simple request, e.g. get ticker info. 

```
exchange.GetTickerAsync("BTC-USD")
```

Keys were generated here. 
https://public.sandbox.exchange.coinbase.com/apikeys

Considering [recent changes](https://github.com/DigitalRuby/ExchangeSharp/issues/810) in Coinbase, is this initialization still valid or I need to generate signature myself using `CryptoUtility` and somehow include it as a bearer token in every request?

**Comment by vslee** [comment]
@artemiusgreat, are you using Coinbase Exchange (for businesses) or Coinbase Advanced (for individuals)?
